import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Form from "../components/textform/form";

export default function Home() {
  return (
    <div className={styles.container}>
      <div className={styles.circle}></div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <span>BookBite</span>
        <ul>
          <li>Home</li>
          <li>Apps</li>
          <li>About</li>
          <li>Contact</li>
        </ul>
      </nav>
      <Form />
    </div>
  );
}
